### ISSUE TITLE
1942-43 not working

### ISSUE THREAD

**Issue by bigrico2000** [RetroDriven/MiSTerMAME#6]
Hello, I downloaded script. Everything working except 1942 and 1943. I know they have no mra file just rbf. Put it in "_arcade" and "_arcade\core" still no luck. Any help would be appreciated, thanks.

**Comment by RetroDriven** [comment]
I didn't realize MRA files were removed for both Cores from the Official GitHub. Do the Jotego versions work for you?

**Comment by bigrico2000** [comment]
Haven't tried them.

**Comment by RetroDriven** [comment]
Do you know why the MRA files were removed from the Official GitHub? I can always add them back to my Unofficial folder.

**Comment by bigrico2000** [comment]
I have no idea, but yeah there gone from the official release folder.

**Comment by RetroDriven** [comment]
I'm trying to find more info about it. I think the Jotego versions are more recent and get updated more often anyways.

**Comment by bigrico2000** [comment]
Ok, and thanks for your work definitely really cool. If anything I'll just
build the ROM.

**Comment by RetroDriven** [comment]
You're welcome.

I can always track down the MRA files and add them to the Unofficial folder. I don't know that there would be an advantage over the Jotego versions though. I may still go that route so the option to choose is there.

**Comment by bigrico2000** [comment]
That would be cool, I will also try the Jotego version and see what happens.

**Comment by RetroDriven** [comment]
I just added the 1942 and 1943 MRA files that will point to the non Jotego RBFs

**Comment by bigrico2000** [comment]
Excellent! Thank you very much.

**Comment by RetroDriven** [comment]
You're welcome 😊

**Comment by TheRealYasri** [comment]
I did a fresh install, then ran official updater then your script. The current official script does not seem to download the rdf from the mister-devel repos for 1942 and 1943.
https://github.com/MiSTer-devel/Arcade-1942_MiSTer/tree/master/_releases
https://github.com/MiSTer-devel/Arcade-1943_MiSTer/tree/master/_releases

If I had to guess it is because there are no mra files in the those folders. Which I enabled thru the ini on Locutus73 script, sense he has yet to enable it by default, but plans to very soon, as it is the new system going forward. 

While the gng repo did download and it has two mra files in the folder.
https://github.com/MiSTer-devel/Arcade-GnG_MiSTer/tree/master/releases

Probably best to remove these mra below that depend on the mister-devel repo and updater script, but will no longer work.

├── _Unofficial
    ├── 1942.mra
    ├── 1943 Kai Midway Kaisen.mra
    ├── 1943 The Battle of Midway Mark II.mra
    ├── 1943 The Battle of Midway.mra

Wonder if they plan on removing support for the Ghosts'n Goblins mister-devel release also, sense that is his only other core on mister-devel, that I can see. Also the jotego release is newer anyway.
